# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-01 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('EventDate', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=3)),
                ('ZipCode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='MainApp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=3)),
                ('ZipCode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='PostedByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostedByUser', to='MainApp.User'),
        ),
        migrations.AddField(
            model_name='eventattendant',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersGoing', to='MainApp.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='CreatedByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreatedByUser', to='MainApp.User'),
        ),
    ]
