# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-01 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20190401_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='CreatedByUser',
            new_name='EventByUser',
        ),
        migrations.RenameField(
            model_name='eventcomment',
            old_name='PostedByUser',
            new_name='CommentByUser',
        ),
    ]
