# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-01 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20190401_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='Address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='State',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='ZipCode',
            field=models.CharField(max_length=5),
        ),
    ]
