# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20190401_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendant',
            name='Event',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='CommentByUser',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventAttendant',
        ),
        migrations.DeleteModel(
            name='EventComment',
        ),
    ]
