# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20190522_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Address',
            field=models.CharField(max_length=255),
        ),
    ]
