# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20190522_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventTime',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
