# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_event_eventtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventTime',
            field=models.DateTimeField(max_length=255),
        ),
    ]
