# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20190522_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
