# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20190604_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='UsersGoing',
            field=models.ManyToManyField(related_name='UsersGoing', to='MainApp.User'),
        ),
    ]
