# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_auto_20190605_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventByUser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='UsersGoing',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
