# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0017_auto_20190605_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('EventDate', models.CharField(max_length=255)),
                ('EventTime', models.TimeField(blank=True, null=True)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=3)),
                ('ZipCode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=2)),
                ('City', models.CharField(max_length=20)),
                ('ZipCode', models.CharField(max_length=5)),
                ('Password', models.CharField(default=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='EventByUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventsByUser', to='MainApp.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='UsersGoing',
            field=models.ManyToManyField(related_name='UsersGoing', to='MainApp.User'),
        ),
    ]
