# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-30 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_auto_20190630_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventDate',
        ),
    ]
