# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_remove_event_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ZipCode',
            field=models.IntegerField(max_length=6),
        ),
    ]
