# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-01 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_auto_20190701_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ZipCode',
            field=models.IntegerField(),
        ),
    ]
