# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-01 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_auto_20190701_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
