# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_event_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='./MainApp/images/placehodler.png', upload_to='ProfileImage'),
        ),
    ]
