# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='./MainApp/images/placeholder.png', upload_to='ProfileImage'),
        ),
    ]
