# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_auto_20190702_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='ProfileImage'),
        ),
    ]
