# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-03 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_auto_20190702_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
