# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_auto_20190703_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='ProfileImage'),
        ),
    ]
