# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_auto_20190703_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='RiderImage',
            field=models.ImageField(blank=True, upload_to='RiderImage'),
        ),
    ]
