# Generated by Django 2.2.3 on 2019-07-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0039_auto_20190703_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='RiderImage',
        ),
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, default='/static/MainApp/images/placeholder.png', upload_to='Users/gustavo/Documents/Coding Random Stuff/PyTestApp/main/apps/MainApp/media/RiderImages'),
        ),
    ]
